<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0PxgDZT' shared service.

return $this->privates['.service_locator.0PxgDZT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CommandController::index' => ['privates', '.service_locator.8mkNlYJ', 'get_ServiceLocator_8mkNlYJService.php', true],
    'App\\Controller\\FacebookController::connectAction' => ['privates', '.service_locator.no19fnv', 'get_ServiceLocator_No19fnvService.php', true],
    'App\\Controller\\FacebookController::connectCheckAction' => ['privates', '.service_locator.no19fnv', 'get_ServiceLocator_No19fnvService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\CommandController:index' => ['privates', '.service_locator.8mkNlYJ', 'get_ServiceLocator_8mkNlYJService.php', true],
    'App\\Controller\\FacebookController:connectAction' => ['privates', '.service_locator.no19fnv', 'get_ServiceLocator_No19fnvService.php', true],
    'App\\Controller\\FacebookController:connectCheckAction' => ['privates', '.service_locator.no19fnv', 'get_ServiceLocator_No19fnvService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\CommandController::index' => '?',
    'App\\Controller\\FacebookController::connectAction' => '?',
    'App\\Controller\\FacebookController::connectCheckAction' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\CommandController:index' => '?',
    'App\\Controller\\FacebookController:connectAction' => '?',
    'App\\Controller\\FacebookController:connectCheckAction' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
