<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.W4TB1tB' shared service.

return $this->privates['.service_locator.W4TB1tB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adresse' => ['privates', 'App\\Service\\Adresse', 'getAdresseService.php', true],
], [
    'adresse' => 'App\\Service\\Adresse',
]);
