<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\Adresse' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\Adresse.php';

return $this->privates['App\\Service\\Adresse'] = new \App\Service\Adresse();
