<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ou1dIJr' shared service.

return $this->privates['.service_locator.ou1dIJr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CommandController::index' => ['privates', '.service_locator.8mkNlYJ', 'get_ServiceLocator_8mkNlYJService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\CommandController:index' => ['privates', '.service_locator.8mkNlYJ', 'get_ServiceLocator_8mkNlYJService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\CommandController::index' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\CommandController:index' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
