<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerERBChHe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerERBChHe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerERBChHe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerERBChHe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerERBChHe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ERBChHe',
    'container.build_id' => 'fee71971',
    'container.build_time' => 1573162497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerERBChHe');
