<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTPd60M\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTPd60M/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTPd60M.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTPd60M\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQTPd60M\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QTPd60M',
    'container.build_id' => 'c61951ed',
    'container.build_time' => 1574109207,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTPd60M');
