<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBgedDWy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBgedDWy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBgedDWy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBgedDWy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBgedDWy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BgedDWy',
    'container.build_id' => '32aa3a1e',
    'container.build_time' => 1573253235,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBgedDWy');
